### ISSUE TITLE
Disable digest per default for all users

### ISSUE THREAD

**Issue by cforce** [drewkeller/redmine_digest#14]
We get many complains that yet the users get newsletter although they didn't register for it. Of course they can disbale it, but i think it should be default to be disabled. 
We set active to 0 for all userid we found in table digest _accounts, burt what is with users there is not entry? What will happen on default?
Itz should be active=false if no entry is in table.

**Comment by drewkeller** [comment]
On the configuration screen for the plugin (Administration > Plugins > Configure link under Digest plugin), there is an option "Default setting for users" which is checked by default. It sounds like you want to uncheck it.

I imagine most people would probably want this unchecked, but for my case, I need it checked because 70% of my Redmine users haven't even logged into Redmine :/ but they still need to be notified of changes in the projects.

**Comment by cforce** [comment]
Found it .. tx!

**Comment by cforce** [comment]
I must reopen this issue, because altought in my digest admin settings "Default setting for users Active " is unchecked ..many users which have no entry in database (means they habe no digest settings ever made) still get digests! This is realy bad, becuase many poeple get mails and talking about "spam", so i disbled all digest modules in all projects.

I also habe some cases where the users have in my account setting "receive an email periodically that shows project activity." unchecked, but in database table digest_accounts the field "active" for this user has value true. Reloading webiste , clearing cache ..etc this behave keeps the same .. only setting and unsetting the checkbox in my account seems to fix this "desyncronisation"

**Comment by drewkeller** [comment]
Are you using a rake task or other method to trigger the email?
I probably won't be able to do anything with this for a while due to 
other projects.

**Comment by cforce** [comment]
rake task via cron job, what else?

**Comment by drewkeller** [comment]
Hmm... I merged the pull request, but apparently, that doesn't close the ticket.
