### ISSUE TITLE
An error occurred while sending the digest (undefined method `allowed_to?' for nil:NilClass)

### ISSUE THREAD

**Issue by baol** [drewkeller/redmine_digest#17]
I just installed the digest plugin for redmine on a private redmine 1.3.0 and I get the following error from the rake redmine:send_digest task and from the configuration console when clicking the "Send a test email to your email address".

Warning: Could not find an admin user. Some events might not be visible to the anonymous user
rake aborted!
"undefined method `allowed_to?' for nil:NilClass"

Or, on the web interface: 
"An error occurred while sending the digest (undefined method `allowed_to?' for nil:NilClass)"

**Comment by drewkeller** [comment]
'allowed_to' does not appear anywhere in my code. Without more debug info (such as a trace or line numbers), I can't do anything more with this ticket. I upgraded to redmine 1.3.1 and the digest is working for me, so I'm closing this.

**Comment by baol** [comment]
Please ask yourself: have I asked for a stacktrace? Have I provided info on how to obtain a stacktrace? Do I mind about solving issues?

**Comment by drewkeller** [comment]
How about I just give you a refund of whatever you paid me and you can download the competitor's plugin. Or write your own.

I made this plugin publicly available, but I didn't have to. All changes since the initial release have been to fix issues for other people or implement requests other people have made. It's been working fine for me and the way I intended since the initial release.

That being said, I am willing to try to help you resolve the issue if you can dial down on the rudeness.

Since you ran this from rake, you should have got a stacktrace as part of the error.

**Comment by baol** [comment]
You are right, you didn't have to publish software. I may add that, If you are not willing to support it, you are encouraged not to do so (and please remove it from the web). An unsupported open source project only contributes to Internet pollution.

By the way, I'm sorry if my language seemed rude. I was just expressing my opinion. If it was not clear in the first post my opinion was that closing a bug because I provided no stack trace seems a bit rude (not to say lame) to me. Especially after two months of silence. 

Anyway, don't get me wrong, I know the frustration, perils and work that is needed to effectively manage even the smallest of the open source projects. Keep up the good work.
